### ISSUE TITLE
master password not working with latest version aurora 7.7 

### ISSUE THREAD

**Issue by bsbudhwar** [afterlogic/plugin-master-password#1]
Hi getting error in log as ...

PHP Notice:  Trying to get property of non-object in /public_html/data/plugins/master-password/index.php on line 40, referer: http://mail.example.com/

earlier version working but with 7.7 not working please check and update your code accordingly,

thanks & regards,

Birender

**Comment by afterlogic-support** [comment]
Thanks. Developers will look into this.

**Comment by afterlogic-support** [comment]
The issue has been fixed. We'd appreciate if you let us know whether the error has gone for you.

**Comment by bsbudhwar** [comment]
Working perfectly very fast response great good job.
